package openvpn

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// RenderServerConfig builds the openvpn.conf for a server-side tunnel.
//
// Everything here is emitted from panel-owned values, and every directive is a
// real OpenVPN option: the daemon treats an unknown one as a fatal parse error,
// so a plausible-looking line is not a small mistake — it takes the whole tunnel
// down at startup. directives_test.go pins the emitted set for that reason.
//
// Per-account verification is delegated to a panel-generated script (see
// renderVerifyScript for why OpenVPN forces that choice).
func RenderServerConfig(inst Instance) string {
	var b strings.Builder

	b.WriteString("# Generated by 3x-ui. Do not edit; the panel rewrites this file.\n")
	b.WriteString("mode server\n")
	fmt.Fprintf(&b, "dev %s\n", inst.devName())
	fmt.Fprintf(&b, "proto %s\n", inst.proto())
	b.WriteString("topology subnet\n")
	b.WriteString("dev-type tun\n")

	if inst.CA != "" {
		b.WriteString("ca " + inst.caFile() + "\n")
	}
	if inst.Cert != "" {
		b.WriteString("cert " + inst.certFile() + "\n")
	}
	if inst.Key != "" {
		b.WriteString("key " + inst.keyFile() + "\n")
	}
	if inst.CA != "" {
		b.WriteString("dh none\n")
		b.WriteString("tls-server\n")
	}

	// Keepalive defaults to a server ping and a client response so a dead
	// path drops the session instead of leaving a half-open tunnel that would
	// otherwise count as "connected". In server mode it expands to
	// "ping-restart 120" as well, so there is no separate line for that.
	b.WriteString("keepalive 10 60\n")
	b.WriteString("persist-key\n")
	b.WriteString("persist-tun\n")

	// TLS server mode is required before any certificate option is accepted,
	// and it in turn requires DH parameters. The panel never generates a DH
	// file, so the curve is declared explicitly disabled and the daemon uses
	// ECDH instead — omitting both lines is a fatal "DH file (--dh)" error.
	b.WriteString("tls-server\n")
	b.WriteString("dh none\n")

	if inst.Subnet != "" {
		fmt.Fprintf(&b, "server %s %d\n", inst.Subnet, inst.subnetPrefix())
	}
	if inst.DNSServer != "" {
		fmt.Fprintf(&b, "push \"dhcp-option DNS %s\"\n", inst.DNSServer)
	}
	// Redirect all client traffic into the tunnel, but keep the panel's own
	// control-plane traffic (the management socket is loopback-only anyway)
	// and the client's gateway reachable.
	b.WriteString("push \"redirect-gateway def1\"\n")

	// Authentication: username/password against the panel's accounts. This is
	// what keeps VPN traffic attributable to a panel client for access rules
	// and accounting, so the session's common name is rewritten to the
	// authenticated username below rather than left as the client certificate's
	// CN.
	//
	// script-security must be raised for the verify script to be runnable at
	// all, and 2 is the lowest level that permits one — 3 exists only to pass
	// passwords through the environment, which via-file avoids by design.
	b.WriteString("script-security 2\n")
	b.WriteString("auth-user-pass-verify " + inst.verifyScript() + " via-file\n")
	b.WriteString("username-as-common-name\n")
	if inst.CA == "" {
		b.WriteString("verify-client-cert none\n")
	} else {
		b.WriteString("verify-client-cert require\n")
	}

	// Management interface: loopback only, password protected. The panel needs
	// it to list sessions, disconnect one account, and read counters. The
	// password is passed as a file rather than inline so it never appears in
	// the config, which the daemon prints back verbatim when it reports a
	// parse error.
	fmt.Fprintf(&b, "management 127.0.0.1 %d %s\n", inst.managementPort(), inst.mgmtPasswordFile())

	fmt.Fprintf(&b, "verb %d\n", inst.verbosity())
	return b.String()
}

// subnetPrefix derives the address prefix from the tunnel network, defaulting to
// /24 for an IPv4 network and /64 for IPv6 when the stored network omits one.
func (inst Instance) subnetPrefix() int {
	s := strings.TrimSpace(inst.Subnet)
	if !strings.Contains(s, "/") {
		if strings.Contains(s, ":") {
			return 64
		}
		return 24
	}
	_, bits, _ := strings.Cut(s, "/")
	n, err := strconv.Atoi(bits)
	if err != nil {
		if strings.Contains(s, ":") {
			return 64
		}
		return 24
	}
	return n
}

// managementPort is the loopback port the daemon exposes its management
// interface on. It is derived from the instance id so it stays stable across
// restarts (the panel can reconnect to the same port) while remaining
// unlikely to collide with another panel-managed tunnel.
//
// Exits live in a separate range from inbounds. An exit's id is a hash of its
// outbound tag and can be large, so adding it to the inbound base could leave the
// valid port range; the two ranges also cannot overlap.
func (inst Instance) managementPort() int {
	if inst.ID < 0 {
		return 8705 + (-inst.ID)
	}
	return 7505 + inst.ID
}

func (inst Instance) dir() string {
	return filepath.Join(configDir(), instanceSlug(inst.ID))
}

func (inst Instance) caFile() string   { return filepath.Join(inst.dir(), "ca.pem") }
func (inst Instance) certFile() string { return filepath.Join(inst.dir(), "cert.pem") }
func (inst Instance) keyFile() string  { return filepath.Join(inst.dir(), "key.pem") }
func (inst Instance) authFile() string {
	return filepath.Join(inst.dir(), "auth-users.txt")
}

// verifyScript is the program handed to --auth-user-pass-verify. It sits beside
// the account file it reads so a tunnel's credentials never leave the tunnel's
// own directory.
func (inst Instance) verifyScript() string {
	return filepath.Join(inst.dir(), "verify-user.sh")
}

// mgmtPasswordFile is the management interface's password. It is a file because
// the alternative — the password inline in openvpn.conf — puts the secret in a
// document the daemon reproduces verbatim in error messages.
func (inst Instance) mgmtPasswordFile() string {
	return filepath.Join(inst.dir(), "mgmt.pw")
}

// writeMgmtPassword materialises the management password for a tunnel whose
// config names it. Rewriting the same value is a no-op, so this is safe to call
// on every apply.
func (inst Instance) writeMgmtPassword(password string) error {
	if err := os.MkdirAll(inst.dir(), 0o700); err != nil {
		return err
	}
	return os.WriteFile(inst.mgmtPasswordFile(), []byte(password+"\n"), 0o600)
}

// renderVerifyScript is the body of the account check OpenVPN runs for every
// connecting client.
//
// OpenVPN has no file-only verification: --auth-user-pass-verify names a
// command and the daemon executes it (verify_user_pass_script builds an argv
// from the argument and runs it), so pointing that option at a data file would
// execute the data file. The panel therefore supplies the program itself.
//
// Its properties are deliberate:
//
//   - no interpreter beyond /bin/sh, no network, no configuration: the file's
//     content is fully determined by this renderer, which is what keeps an
//     imported profile from contributing to it;
//   - the presented credentials are compared as read values and never expanded,
//     so a password holding shell metacharacters is matched literally;
//   - every path that is not an exact pair match exits non-zero, including an
//     unreadable account file, so a failure denies the connection instead of
//     admitting it.
//
// OpenVPN passes the temporary file holding the presented pair (username on
// line 1, password on line 2) as $1 when the option is declared as via-file.
func renderVerifyScript(accountFile string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by 3x-ui. Do not edit; the panel rewrites this file.\n")
	b.WriteString("user=$(sed -n 1p \"$1\")\n")
	b.WriteString("pass=$(sed -n 2p \"$1\")\n")
	b.WriteString("while IFS= read -r entry; do\n")
	b.WriteString("\tcase \"$entry\" in\n")
	b.WriteString("\t*\" \"*) ;;\n")
	b.WriteString("\t*) continue ;;\n")
	b.WriteString("\tesac\n")
	b.WriteString("\tname=${entry%% *}\n")
	b.WriteString("\tsecret=${entry#* }\n")
	b.WriteString("\tif [ \"$name\" = \"$user\" ] && [ \"$secret\" = \"$pass\" ]; then\n")
	b.WriteString("\t\texit 0\n")
	b.WriteString("\tfi\n")
	b.WriteString("done < " + shellQuote(accountFile) + "\n")
	b.WriteString("exit 1\n")
	return b.String()
}

// shellQuote wraps a path for use inside double quotes in a generated script.
// The directory is derived from panel configuration rather than from an
// imported profile, but a space in it must still not split the redirection.
func shellQuote(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
}

// RenderAuthUsers builds the auth-user-pass-verify file. The panel's account
// email is the username, so openvpn reports it as the client's common name and
// the panel can attribute the session — and its bytes — back to that account.
func RenderAuthUsers(clients []ClientConfig) string {
	var b strings.Builder
	b.WriteString("# Generated by 3x-ui. username password\n")
	active := make([]ClientConfig, 0, len(clients))
	for _, c := range clients {
		if c.Enabled && strings.TrimSpace(c.Username) != "" && c.Password != "" {
			active = append(active, c)
		}
	}
	sort.Slice(active, func(i, j int) bool { return active[i].Username < active[j].Username })
	for _, c := range active {
		fmt.Fprintf(&b, "%s %s\n", c.Username, c.Password)
	}
	return b.String()
}

// RenderClientConfig builds the client-side openvpn.conf for an exit tunnel.
//
// The allowlisted profile parameters are emitted explicitly; nothing from the
// imported profile is passed through verbatim.
func RenderClientConfig(inst Instance, p profileParams) string {
	var b strings.Builder
	b.WriteString("# Generated by 3x-ui. Do not edit; the panel rewrites this file.\n")
	b.WriteString("client\n")
	fmt.Fprintf(&b, "dev %s\n", inst.devName())
	fmt.Fprintf(&b, "dev-type tun\n")

	proto := p.Proto
	if strings.EqualFold(inst.RemoteProto, "tcp") {
		proto = "tcp"
	}
	if strings.EqualFold(inst.Proto, "tcp") {
		proto = "tcp"
	}
	fmt.Fprintf(&b, "proto %s\n", proto)

	host := strings.TrimSpace(inst.Remote)
	port := inst.RemotePort
	if host == "" {
		host = p.Remote
		port = p.RemotePort
	}
	fmt.Fprintf(&b, "remote %s %d\n", host, port)

	if p.CA != "" {
		b.WriteString("ca " + filepath.Join(inst.clientDir(), "ca.pem") + "\n")
	}
	if p.Cert != "" {
		b.WriteString("cert " + filepath.Join(inst.clientDir(), "cert.pem") + "\n")
	}
	if p.Key != "" {
		b.WriteString("key " + filepath.Join(inst.clientDir(), "key.pem") + "\n")
	}
	if p.TLSAuth != "" {
		b.WriteString("tls-auth " + filepath.Join(inst.clientDir(), "tls-auth.pem") + " 1\n")
	}
	// An exit tunnel that accepted any server certificate would be trivially
	// interceptable, so a pinned CA is mandatory rather than advisory.
	if p.CA != "" {
		if p.RemoteTLS == "" {
			b.WriteString("remote-cert-tls server\n")
		} else {
			fmt.Fprintf(&b, "remote-cert-tls %s\n", p.RemoteTLS)
		}
	}
	if p.VerifyX509 != "" {
		fmt.Fprintf(&b, "verify-x509-name %s name\n", p.VerifyX509)
	}

	// Credentials never appear inline in the generated config: they go into a
	// 0600 file so the config can be read for debugging without leaking a
	// password into a log or an API response.
	user := inst.Username
	if user == "" {
		user = p.Username
	}
	if user != "" || p.AuthUserPass {
		b.WriteString("auth-user-pass " + filepath.Join(inst.clientDir(), "auth.txt") + "\n")
	}

	if p.Cipher != "" {
		fmt.Fprintf(&b, "cipher %s\n", p.Cipher)
	}
	if p.Auth != "" {
		fmt.Fprintf(&b, "auth %s\n", p.Auth)
	}
	if p.CompLzo != "" && p.CompLzo != "no" {
		fmt.Fprintf(&b, "comp-lzo %s\n", p.CompLzo)
	}
	if p.Keepalive != "" {
		fmt.Fprintf(&b, "keepalive %s\n", p.Keepalive)
	} else {
		b.WriteString("keepalive 10 60\n")
	}
	if p.Float {
		b.WriteString("float\n")
	}
	if p.TLSVersion != "" {
		// The profile carries --tls-version-min (there is no bare
		// --tls-version); emitting the directive under its real name is the
		// difference between the daemon honouring the floor and refusing the
		// config outright.
		fmt.Fprintf(&b, "tls-version-min %s\n", p.TLSVersion)
	}

	b.WriteString("nobind\n")
	b.WriteString("persist-key\n")
	b.WriteString("persist-tun\n")
	b.WriteString("resolv-retry infinite\n")
	b.WriteString("connect-retry 5 30\n")

	// The exit's traffic must all go through the tunnel; without this the
	// daemon would leave a default route pointing at the real gateway and
	// silently bypass the VPN. def1 installs 0.0.0.0/1 and 128.0.0.0/1,
	// which covers every IPv4 destination.
	b.WriteString("redirect-gateway def1\n")

	// IPv4 routes are only half of the job. A dual-stack host would otherwise
	// keep an untouched IPv6 default route and send every IPv6 flow — often
	// including the name lookups the IPv4 routes were meant to hide — straight
	// out the real interface. block-ipv6 sends IPv6 into the tunnel instead and
	// answers it with ICMPv6 "no route to host": the panel cannot promise the
	// peer carries IPv6, so the packets are refused rather than allowed around
	// the tunnel. Failing to reach a destination is the correct outcome for an
	// exit; reaching it on the wrong interface is not.
	b.WriteString("block-ipv6\n")

	// Management interface: loopback only, password carried in a file for the
	// same reason as the server side — the daemon quotes the config line when
	// it reports an error, and a password must not be one line away from a log
	// file. It is how the panel reads an exit's counters and stops it.
	fmt.Fprintf(&b, "management 127.0.0.1 %d %s\n", inst.managementPort(), inst.mgmtPasswordFile())

	// An exit authenticates with its own --auth-user-pass credentials and runs
	// no hooks, so nothing in this config is permitted to run a program.
	b.WriteString("script-security 0\n")

	verb := inst.verbosity()
	if p.Verb > verb {
		verb = p.Verb
	}
	fmt.Fprintf(&b, "verb %d\n", verb)
	return b.String()
}

func (inst Instance) clientDir() string {
	return filepath.Join(configDir(), instanceSlug(inst.ID))
}

// writeSecretFiles materialises the PEM blobs and credential files the config
// references. Everything is written 0600 inside the tunnel's own directory,
// because these files are the tunnel's entire secret material.
func (inst Instance) writeSecretFiles(p profileParams, clients []ClientConfig) error {
	dir := inst.dir()
	if inst.isServer() {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return err
		}
		if err := writeIfSet(inst.caFile(), inst.CA); err != nil {
			return err
		}
		if err := writeIfSet(inst.certFile(), inst.Cert); err != nil {
			return err
		}
		if err := writeIfSet(inst.keyFile(), inst.Key); err != nil {
			return err
		}
		// The account file must exist even with no clients: an empty list
		// denies everyone, which is the correct shape for "no accounts yet",
		// while a missing file would be an unhandled case.
		if err := os.WriteFile(inst.authFile(), []byte(RenderAuthUsers(clients)), 0o600); err != nil {
			return err
		}
		// The verifier is executed rather than read, so both its shebang and
		// its mode are load-bearing: 0700 keeps it out of the reach of
		// anything that is not the daemon or the panel.
		return os.WriteFile(inst.verifyScript(), []byte(renderVerifyScript(inst.authFile())), 0o700)
	}

	dir = inst.clientDir()
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	if err := writeIfSet(filepath.Join(dir, "ca.pem"), p.CA); err != nil {
		return err
	}
	if err := writeIfSet(filepath.Join(dir, "cert.pem"), p.Cert); err != nil {
		return err
	}
	if err := writeIfSet(filepath.Join(dir, "key.pem"), p.Key); err != nil {
		return err
	}
	if err := writeIfSet(filepath.Join(dir, "tls-auth.pem"), p.TLSAuth); err != nil {
		return err
	}
	user := inst.Username
	if user == "" {
		user = p.Username
	}
	if user == "" {
		return nil
	}
	pass := inst.Password
	if pass == "" {
		pass = p.Password
	}
	return os.WriteFile(filepath.Join(dir, "auth.txt"), []byte(user+"\n"+pass+"\n"), 0o600)
}

func writeIfSet(path, content string) error {
	if strings.TrimSpace(content) == "" {
		return nil
	}
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return os.WriteFile(path, []byte(content), 0o600)
}
